BEGIN;

CREATE TABLE public.clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    phone VARCHAR(32),
    email VARCHAR(254),

    CONSTRAINT chk_clients_full_name_not_blank
        CHECK (btrim(full_name) <> ''),
    CONSTRAINT chk_clients_phone_not_blank
        CHECK (phone IS NULL OR btrim(phone) <> ''),
    CONSTRAINT chk_clients_email_not_blank
        CHECK (email IS NULL OR btrim(email) <> ''),
    CONSTRAINT chk_clients_contact_present
        -- NULLIF на данном примере если номер пустой, то вернёт NULL
        CHECK (
            NULLIF(btrim(phone), '') IS NOT NULL
            OR NULLIF(btrim(email), '') IS NOT NULL
        )
);

CREATE TABLE public.drivers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    phone VARCHAR(32) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT chk_drivers_full_name_not_blank
        CHECK (btrim(full_name) <> ''),
    CONSTRAINT chk_drivers_phone_not_blank
        CHECK (btrim(phone) <> '')
);

CREATE TABLE public.operators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    phone VARCHAR(32) NOT NULL,

    CONSTRAINT chk_operators_full_name_not_blank
        CHECK (btrim(full_name) <> ''),
    CONSTRAINT chk_operators_phone_not_blank
        CHECK (btrim(phone) <> '')
);

CREATE TABLE public.transportation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    driver_id BIGINT,
    operator_id BIGINT NOT NULL,
    cargo_description VARCHAR(500) NOT NULL,
    -- 12 это макс кол-во цифр в числе, а 3 макс кол-во цифр после запятой
    weight_kg NUMERIC(12, 3) NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    planned_delivery_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    pickup_address VARCHAR(300) NOT NULL,
    delivery_address VARCHAR(300) NOT NULL,

    CONSTRAINT fk_transportation_requests_client
        FOREIGN KEY (client_id)
        REFERENCES public.clients (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_transportation_requests_driver
        FOREIGN KEY (driver_id)
        REFERENCES public.drivers (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_transportation_requests_operator
        FOREIGN KEY (operator_id)
        REFERENCES public.operators (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_transportation_requests_cargo_not_blank
        CHECK (btrim(cargo_description) <> ''),
    CONSTRAINT chk_transportation_requests_positive_weight
        CHECK (weight_kg > 0),
    CONSTRAINT chk_transportation_requests_positive_price
        CHECK (price > 0),
    CONSTRAINT chk_transportation_requests_delivery_after_creation
        CHECK (planned_delivery_at > created_at),
    CONSTRAINT chk_transportation_requests_status
        CHECK (
            status IN (
                'CREATED',
                'APPROVED',
                'IN_TRANSIT',
                'DELIVERED',
                'CANCELLED'
            )
        ),
    CONSTRAINT chk_transportation_requests_pickup_not_blank
        CHECK (btrim(pickup_address) <> ''),
    CONSTRAINT chk_transportation_requests_delivery_not_blank
        CHECK (btrim(delivery_address) <> ''),
    CONSTRAINT chk_transportation_requests_different_addresses
        CHECK (
            lower(btrim(pickup_address))
            <> lower(btrim(delivery_address))
        ),

    -- Новая заявка всегда создаётся без назначенного доставщика.
    CONSTRAINT chk_transportation_requests_created_without_driver
        CHECK (status <> 'CREATED' OR driver_id IS NULL),

    -- Начатая или завершённая перевозка обязательно сохраняет доставщика.
    CONSTRAINT chk_transportation_requests_started_with_driver
        CHECK (
            status NOT IN ('IN_TRANSIT', 'DELIVERED')
            OR driver_id IS NOT NULL
        )
);

-- Внешние ключи PostgreSQL автоматически не индексирует
CREATE INDEX idx_transportation_requests_client_id
    ON public.transportation_requests (client_id);

CREATE INDEX idx_transportation_requests_operator_id
    ON public.transportation_requests (operator_id);

CREATE INDEX idx_transportation_requests_driver_id
    ON public.transportation_requests (driver_id)
    WHERE driver_id IS NOT NULL;

CREATE INDEX idx_transportation_requests_status
    ON public.transportation_requests (status);

CREATE INDEX idx_transportation_requests_planned_delivery_at
    ON public.transportation_requests (planned_delivery_at);

-- Ускоряет получение свободных заявок в порядке плановой доставки
CREATE INDEX idx_transportation_requests_available
    ON public.transportation_requests (planned_delivery_at)
    -- одобренная заявки у которого ещё нет назначенного водителя
    WHERE status = 'APPROVED' AND driver_id IS NULL;

COMMIT;
